
# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: MySql8035
      MYSQL_DATABASE: furniture
    ports:
      - "3306:3306"
